# Generated by Django 3.0.8 on 2020-07-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nick',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
