# Generated by Django 3.0.8 on 2020-08-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_auto_20200721_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
